config {
  name: "seo_gsc_query",
  schema: "seo_dashboard_02_raw",
  type: "incremental",
  uniqueKey: ["day", "site", "query"]
}

with up_to_date as (
  select
    * except (dt_created, dt_updated, dt_filename),
    row_number() over (
      partition by day, site, query
      order by dt_updated desc
    ) rank
  from ${ref("seo_dashboard_01_temp", "temp_seo_gsc_query")}
)
select 
  * except (rank)
from up_to_date
where rank = 1
