config {
  type: "incremental",
  schema: "seo_dashboard_04_rpt",
  name: "seo_forecasting",
  uniqueKey: ["Country", "year_month"],
  assertions: {
    uniqueKey: ["Country", "year_month"]
  }
}

select 
	tmp.Country
	, PARSE_DATE('%Y-%m', CONCAT(tmp.parsed_year, '-', tmp.parsed_month)) as year_month
	, tmp.Sessions
	, c.ID_Country
from ${ref("seo_dashboard_02_raw", "seo_forecasting")} tmp
left join ${ref("seo_dashboard_04_rpt", "D_country")} c
on c.Country = tmp.Country